### PR TITLE
Publish

### PR DESCRIPTION
**Pull request by U007D**
I've written the documentation I think it should have, as well as implemented variations on the trait so that users can validate their argument by consumption, by ref or by mut_ref.

LMK if you're ok with my publishing this (the new fluent_validator) to crates.io.

### CODE REVIEW

**Comment by U007D** [comment]
LGTM

**Comment by bgbahoue** [comment]
Hello sir,

I have a 2 main remarks. 

A) the examples of your README.md don't compile and I think they should. 

My suggestion would be to add the content of your README.md into the documentation of assayer's module (ie in lib.rs using //!). That way we can
(1) get documentation available on docs.rs
(2) allow cargo to compile your examples (ˋ`ˋrust code is compiled when you run `cargo test` unless you add `,ignore ˋ)

B) On a more optional notice I feel that all the Validator traits should be merged as one. I'll give it a try. 

I'll publish my changed in a separate branch for your review, I will work on that in the plane

**Comment by bgbahoue** [comment]
just pushed branch "feature/doc" with the changes I propose for the README.md and the doc of the main module.

I'm wondering whether we shouldn't add some comments to the main classes as well in case some people prefer to navigate the docs.rs instead of just the main README.md / module documentation or for later reference.

any thoughts on that?

**Comment by U007D** [comment]
Somehow I missed these comments until now.
* agreed on the example code needing to compile.  This is fixed.
* not entirely sure about putting the docs in the code itself (there is a lot of explanatory text).  I'll take a look to see if it feels too cluttered.  In the meantime, I don't see this issue as a ship-blocker.
* I'm not sure I follow your meaning on unifying the traits.  Since they each have different consumption behavior, how could they be unified?

**Comment by bgbahoue** [comment]
On your last point I was thinking a trait that exposes the 3 validate methods (owned, ref, mut ref) as your needs may change with time. But that would suppose having a blanket implement on all but one function (same logic as Iterator trait exposing a lot of method but requesting you to only implement ˋnext()ˋ

Not sure if it would make sense or be feasible. Just felt it would be more "elegant" :)

**Comment by U007D** [comment]
Ah, I see.  Yes, I tried, and the closest I could get was the last code example I provide in the docs.  The "'blanket impl" has to be on a per-trait-implementation basis.  So it's not really a blanket impl, but a blanket impl only for a given impl.

If I could find a way to truly generalize that, you're right--that would be elegant.  I'll give it some more thought--thank you sir!

**Comment by bgbahoue** [comment]
I was probably not clear enough on what I called blanket implementation but it's no biggy. What I meant really was a design like the Iterator trait when 90% of the trait methods are using the next() function yet the trait itself expose a dozen a method. 

Would be cool to do something like 
trait Validator {
fn implement_me();
fn validate(self) { // do something using implement_me() only }
fn validate_ref(&self) { // do something using implement_me() only }
fn validate_mut(& mut self) { // do something using implement_me() only }
}

I'll add it to the list of things I need to think at when I'll have time :)

**Comment by U007D** [comment]
Yep, you were clear.  :)

**Comment by bgbahoue** [comment]
:)

**Pull request merged**
